language: node_js
node_js: "node"

install:
- npm install newman
- yarn

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node ./src/index.js &
- node_modules/.bin/newman run tests/postman-demo-tests.postman_collection.json

deploy:
  provider: heroku
  api_key:
    secure: "jslaBIUQ6EhMd42rGbiO3i8WpRz6buWnx7Z1zqmtyUrJSyoJjh+z5SYgWKeWxdEpZ1OHr9v9/M0LVX7FD2arjaVFY3A/AMx9UlfWbRIKYd+kadeARCZVrlhChfq0m/leINk4vZdcJja1DEqPscgsmvyqeKdohFM0Ny5YtdjMBr2UG3Lx5BEcZYxaEXc55U7mgirXtqIIczdoh8EH7/N+bdHb4QJjWCYJRqKg5Vkdla/XYAeG0gEKyDhViT4h9vjp78AohqmOiYpboqRMX4pDkLDhsnpQgFVHJ2Zzxa6CaXJI6nZP8D+1lPDNll44OPNfHD/wIpjBwJBGtC0cqMPx+rOOCmBkk3MLa5xTImdwyQnPRLSs1o2ZD2X3i4cuQxeh88WbGP96RTi1Km1PMJi298hGVV9JAGdubHVwKF7+Kk0sWf3mBol7VJkeoOxg6062csyTT1JAEZX7S4Lp8RPqilFDE7OMN1eWEzhYPGmFSrOSFk6GU50wBUXQw0y1YPRXNAeTCG9GTisGVuJj0KYm/Ski3YoJyBAonu6N0c9W9Gj2iu11dcl5iHdFfMMUrCnyigv4cGrouzFG5wih13jUFsEoM072/Sgv8SswfOCVT/LWuCsuB554R0zkXbuWqgT1N8+grtlh91tsLR5siOUUvJ7x8JLnkOg0oebWo7XXEQ8="
  app: postman-ci-example