language: node_js
node_js:
- "node"

install:
- npm install newman
- yarn

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run tests/postman-demo-tests.postman_collection.json
- yarn start